#===============================================================================
# export variable
#===============================================================================



#===============================================================================
# rules
#===============================================================================
.PHONY: all clean

all:
	make -C tryout
	$(AT)make -C coverflow
#	$(AT)make -C coverflow_vertical
	$(AT)make -C cylinder

clean:
#	$(AT)make -C coverflow clean
#	$(AT)make -C coverflow_vertical clean
#	$(AT)make -C cylinder clean

